name: Android Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build type"
        required: true
        default: "debug"
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission
        run: chmod +x gradlew

      # Debug build
      - name: Build Debug APK
        if: ${{ github.event.inputs.build_type == 'debug' }}
        run: ./gradlew assembleDebug

      # Release build
      - name: Decode Keystore
        if: ${{ github.event.inputs.build_type == 'release' }}
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > keystore.jks

      - name: Build Release APK
        if: ${{ github.event.inputs.build_type == 'release' }}
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: keystore.jks
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk